import { KEYWORDS, SUPPORTED_OPERATORS } from '../shared/constants';

export { KEYWORDS };

export const MONACO_OPERATORS = [
  SUPPORTED_OPERATORS.EQUAL,
  SUPPORTED_OPERATORS.NOT_EQUAL,
  SUPPORTED_OPERATORS.LESS_THAN,
  SUPPORTED_OPERATORS.LESS_THAN_OR_EQUAL,
  SUPPORTED_OPERATORS.GREATER_THAN,
  SUPPORTED_OPERATORS.GREATER_THAN_OR_EQUAL,
  SUPPORTED_OPERATORS.GLOB,
  SUPPORTED_OPERATORS.NOT_GLOB,
  '&&',
  '||',
  '!',
];
