#!/usr/bin/env bash
set -e

# yarn test:pw:docker ui/address/AddressTokenTransfers.pw.tsx --update-snapshots
# yarn test:pw:docker ui/address/AddressTxs.pw.tsx --update-snapshots
yarn test:pw:docker ui/snippets/searchBar/SearchBarDesktop.pw.tsx --update-snapshots


