#!/usr/bin/env bash
set -e

yarn test:pw:docker ui/home/LatestTxs.pw.tsx --update-snapshots
yarn test:pw:docker ui/home/latestZetaChainCCTX/LatestZetaChainCCTXs.pw.tsx --update-snapshots
yarn test:pw:docker ui/pages/Blocks.pw.tsx --update-snapshots
yarn test:pw:docker ui/pages/Entity.pw.tsx --update-snapshots
yarn test:pw:docker ui/shared/chart/ChartWidget.pw.tsx --update-snapshots
yarn test:pw:docker ui/snippets/header/Burger.pw.tsx --update-snapshots
yarn test:pw:docker ui/snippets/header/HeaderDesktop.pw.tsx --update-snapshots
yarn test:pw:docker ui/snippets/header/HeaderMobile.pw.tsx --update-snapshots
yarn test:pw:docker ui/snippets/navigation/horizontal/NavigationDesktop.pw.tsx --update-snapshots
yarn test:pw:docker ui/snippets/navigation/vertical/NavigationDesktop.pw.tsx --update-snapshots
yarn test:pw:docker ui/snippets/searchBar/SearchBarMobile.pw.tsx --update-snapshots
yarn test:pw:docker ui/snippets/topBar/NetworkMenu.pw.tsx --update-snapshots
yarn test:pw:docker ui/snippets/topBar/TopBar.pw.tsx --update-snapshots
yarn test:pw:docker ui/tx/details/TxInfo.pw.tsx --update-snapshots
yarn test:pw:docker ui/txs/TxsListItem.pw.tsx --update-snapshots
yarn test:pw:docker ui/txs/TxsTable.pw.tsx --update-snapshots
yarn test:pw:docker ui/zetaChain/ZetaChainCCTXsTab.pw.tsx --update-snapshots

